version: '3.9'

services:
  postgres:
    container_name: api_books_postgres
    image: postgres:13.2-alpine
    volumes:
      - ./.docker/local/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: api_books_app
      POSTGRES_PASSWORD: 123{@f
      POSTGRES_DB: api_books

  nginx:
    container_name: api_books_nginx
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www
      - ./.docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    container_name: api_books_app
    restart: always
    build:
      context: ./.docker/local/app
    depends_on:
        - postgres
    volumes:
      - ./:/var/www


volumes:
  dbdata: